substitutions:
  devicename: temp_greenhouse
  friendly_name: temp_greenhouse_hlavni
  device_description: temp_greenhouse_hlavni

esphome:
  name: ${devicename}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret AP_Password

  manual_ip:
<<<<<<< HEAD
      static_ip: 192.168.1.104
      gateway: 192.168.1.1
=======
      static_ip: 192.168.5.103
      gateway: 192.168.5.1
>>>>>>> 761a3b2d453ddee8003ae4d990083d01e25efea4
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Web server can be removed after enabling HA API
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret OTA_Password

ota:
  password: !secret OTA_Password

# Enable time component for use by daily power sensor
time:
  - platform: homeassistant
    id: homeassistant_time

#untested based on https://community.home-assistant.io/t/esphome-with-esp-01-dht11/109037/2
sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "greenhouse_temperature"
      on_value:
        then:
          - mqtt.publish:
              topic: greenhouse_state/temp
              payload: |- 
                id("greenhouse_temperature").state
    humidity:
      name: "greenhouse_humidity"
      on_value: 
        then:
          - mqtt.publish:
              topic: greenhouse_state/humidity
              payload: |-
                id("greenhouse_humidity").state
    update_interval: 60s

mqtt:
  broker: !secret mqtt_host
  username: temp_greenhouse
  password: !secret mqtt_password_temp
  discovery: true