substitutions:
  devicename: wled_main
  friendly_name: wled_main_main
  device_description: wled_main_main

esphome:
  name: ${devicename}
  comment: ${device_description}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret AP_Password

  manual_ip:
      static_ip: 192.168.1.103
      gateway: 192.168.1.1
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Web server can be removed after enabling HA API
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret OTA_Password

ota:
  password: !secret OTA_Password

# Enable time component for use by daily power sensor
time:
  - platform: homeassistant
    id: homeassistant_time

#untested based on https://community.home-assistant.io/t/esphome-with-esp-01-dht11/109037/2
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: D0
    num_leds: 31
    rgb_order: BRG
    name: "FastLED WS2812 Light"

wled: